const data = {
  english: [
    { id: 1, name: "i\u02D0", value: "i\u02D0", specialFeature: false },
    { id: 2, name: "\u026A", value: "\u026A", specialFeature: false },
    { id: 3, name: "u\u02D0", value: "u\u02D0", specialFeature: false },
    { id: 4, name: "ʊ", value: "ʊ", specialFeature: false },
    { id: 5, name: "ə", value: "ə", specialFeature: false },
    { id: 6, name: "ə\u02D0", value: "ə\u02D0", specialFeature: false },
    { id: 7, name: "ɔ\u02D0", value: "ɔ\u02D0", specialFeature: false },
    { id: 8, name: "e", value: "e", specialFeature: false },
    { id: 9, name: "eə", value: "eə", specialFeature: false },
    { id: 10, name: "ʌ", value: "ʌ", specialFeature: false },
    {
      id: 11,
      name: "\u0251\u02D0",
      value: "\u0251\u02D0",
      specialFeature: false,
    },
    {
      id: 12,
      name: "\u0251\u02D0r",
      value: "\u0251\u02D0r",
      specialFeature: false,
    },
    { id: 13, name: "æ", value: "æ", specialFeature: false },
    { id: 14, name: "\u026Aə", value: "\u026Aə", specialFeature: false },
    { id: 15, name: "e\u026A", value: "e\u026A", specialFeature: false },
    { id: 16, name: "a\u026A", value: "a\u026A", specialFeature: false },
    { id: 17, name: "ɔ\u026A", value: "ɔ\u026A", specialFeature: false },
    { id: 18, name: "aʊ", value: "aʊ", specialFeature: false },
    { id: 19, name: "oʊ", value: "oʊ", specialFeature: false },
    { id: 20, name: "ʊə", value: "ʊə", specialFeature: false },
    { id: 21, name: "f", value: "f", specialFeature: false },
    { id: 22, name: "v", value: "v", specialFeature: false },
    { id: 23, name: "θ", value: "θ", specialFeature: false },
    { id: 24, name: "ð", value: "ð", specialFeature: false },
    { id: 25, name: "s", value: "s", specialFeature: false },
    { id: 26, name: "z", value: "z", specialFeature: false },
    { id: 27, name: "ʃ", value: "ʃ", specialFeature: false },
    { id: 28, name: "tʃ", value: "tʃ", specialFeature: false },
    { id: 29, name: "ʒ", value: "ʒ", specialFeature: false },
    { id: 30, name: "dʒ", value: "dʒ", specialFeature: false },
    { id: 31, name: "h", value: "h", specialFeature: false },
    { id: 32, name: "p", value: "p", specialFeature: false },
    { id: 33, name: "b", value: "b", specialFeature: false },
    { id: 34, name: "d", value: "d", specialFeature: false },
    { id: 35, name: "t", value: "t", specialFeature: false },
    { id: 36, name: "k", value: "k", specialFeature: false },
    { id: 37, name: "\u0261", value: "\u0261", specialFeature: false },
    { id: 38, name: "w", value: "w", specialFeature: false },
    { id: 39, name: "r", value: "r", specialFeature: false },
    { id: 40, name: "j", value: "j", specialFeature: false },
    { id: 41, name: "l", value: "l", specialFeature: false },
    { id: 42, name: "m", value: "m", specialFeature: false },
    { id: 43, name: "n", value: "n", specialFeature: false },
    { id: 44, name: "ŋ", value: "ŋ", specialFeature: false },
    { id: 45, name: "⏝", value: "⏝", specialFeature: true },
    { id: 46, name: "\u258F", value: "\u23B8", specialFeature: true },
    { id: 47, name: "\u2502", value: "\u2502", specialFeature: true },
    { id: 48, name: "\u2B5D", value: "\u2B5D", specialFeature: true },
    { id: 49, name: "\u2B5C", value: "\u2B5C", specialFeature: true },
  ],
  chinese: [
    { id: 1, name: "\u0304", value: "\u0304", specialFeature: false },
    { id: 2, name: "\u0301", value: "\u0301", specialFeature: false },
    { id: 3, name: "\u030C", value: "\u030C", specialFeature: false },
    { id: 4, name: "\u0300", value: "\u0300", specialFeature: false },
    { id: 5, name: "a", value: "a", specialFeature: false },
    { id: 6, name: "i", value: "i", specialFeature: false },
    { id: 7, name: "u", value: "u", specialFeature: false },
    { id: 8, name: "ü", value: "ü", specialFeature: false },
    { id: 9, name: "o", value: "o", specialFeature: false },
    { id: 10, name: "e", value: "e", specialFeature: false },
    { id: 11, name: "ai", value: "ai", specialFeature: false },
    { id: 12, name: "ao", value: "ao", specialFeature: false },
    { id: 13, name: "ou", value: "ou", specialFeature: false },
    { id: 14, name: "ei", value: "ei", specialFeature: false },
    { id: 15, name: "ui", value: "ui", specialFeature: false },
    { id: 16, name: "ue", value: "ue", specialFeature: false },
    { id: 17, name: "ua", value: "ua", specialFeature: false },
    { id: 18, name: "uo", value: "uo", specialFeature: false },
    { id: 19, name: "ia", value: "ia", specialFeature: false },
    { id: 20, name: "iu", value: "iu", specialFeature: false },
    { id: 21, name: "b", value: "b", specialFeature: false },
    { id: 22, name: "p", value: "p", specialFeature: false },
    { id: 23, name: "m", value: "m", specialFeature: false },
    { id: 24, name: "f", value: "f", specialFeature: false },
    { id: 25, name: "d", value: "d", specialFeature: false },
    { id: 26, name: "t", value: "t", specialFeature: false },
    { id: 27, name: "n", value: "n", specialFeature: false },
    { id: 28, name: "l", value: "l", specialFeature: false },
    { id: 29, name: "g", value: "g", specialFeature: false },
    { id: 30, name: "k", value: "k", specialFeature: false },
    { id: 31, name: "ng", value: "ng", specialFeature: false },
    { id: 32, name: "h", value: "h", specialFeature: false },
    { id: 33, name: "j", value: "j", specialFeature: false },
    { id: 34, name: "q", value: "q", specialFeature: false },
    { id: 35, name: "x", value: "x", specialFeature: false },
    { id: 36, name: "zh", value: "zh", specialFeature: false },
    { id: 37, name: "ch", value: "ch", specialFeature: false },
    { id: 38, name: "sh", value: "sh", specialFeature: false },
    { id: 39, name: "r", value: "r", specialFeature: false },
    { id: 40, name: "z", value: "z", specialFeature: false },
    { id: 41, name: "c", value: "c", specialFeature: false },
    { id: 42, name: "s", value: "s", specialFeature: false },
    { id: 43, name: "\u3002", value: "\u3002", specialFeature: false },
    { id: 44, name: "\u3001", value: "\u3001", specialFeature: false },
    { id: 45, name: "\u300C", value: "\u300C", specialFeature: false },
    { id: 46, name: "\u300D", value: "\u300D", specialFeature: false },
    { id: 47, name: "\u2501", value: "\u2501", specialFeature: true },
    { id: 48, name: "\u2570", value: "\u2570", specialFeature: true },
    { id: 49, name: "\u2571", value: "\u2571", specialFeature: true },
    { id: 50, name: "\u2572", value: "\u2572", specialFeature: true },
    { id: 51, name: "\u2022", value: "\u2022", specialFeature: true },
    { id: 52, name: "\u2B5D", value: "\u2B5D", specialFeature: true },
    { id: 53, name: "\u2B5C", value: "\u2B5C", specialFeature: true },
  ],
};
export default data;
